# Generated by Django 5.1.7 on 2025-03-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalstatus',
            name='processedReceptionTime',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='対応中患者の受付時間'),
        ),
    ]
